version: "3"
services:
  backend:
    container_name: backend 
    build:
        context: ./node-server
    depends_on:
      - db  
    # volumes:
    #   - ./backend:/usr/app
    #   - /usr/app/node_modules
    environment:  
      - MONGO_URL=mongodb://db:27017/listings
      - APP_PORT=80
    ports:
      - '9000:9000' 

  db:
    container_name: db
    image: mongo:4.0
    restart: always

  frontend:
    container_name: frontend
    build:
      context: ./vue-client
    # volumes:
    #   - ./frontend:/app
    #   - /app/node_modules
    ports:
      - '8080:8080'
    environment:  
      - BACKEND_URL=http://localhost/api/listings